version: '3'
services:
  db:
    image: postgres:13
    ports:
      - "5555:5432"
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      POSTGRES_DB: catalog